# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np

In [6]:
np.random.randint(0, 20, size = (4, 7))

array([[ 4, 10, 12, 18,  3,  0, 12],
       [ 0,  8,  6,  4,  2,  1, 11],
       [ 8, 17,  1, 10, 17,  6,  8],
       [ 7,  1,  9, 11,  6, 16, 11]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
np.random.randint(0, 10, size = (8, 10))

array([[3, 7, 9, 1, 9, 6, 9, 3, 2, 9],
       [7, 8, 9, 7, 8, 3, 1, 5, 3, 9],
       [1, 4, 2, 3, 9, 4, 1, 5, 4, 1],
       [1, 4, 7, 9, 4, 7, 6, 8, 7, 8],
       [0, 9, 4, 7, 8, 4, 5, 2, 4, 6],
       [6, 1, 2, 9, 6, 8, 1, 9, 0, 2],
       [5, 2, 4, 5, 9, 2, 1, 7, 5, 1],
       [9, 2, 8, 5, 1, 4, 7, 9, 6, 2]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [10]:
import matplotlib.pyplot as pl
from mpl_toolkits.mplot3d import Axes3D

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [5]:
import numpy as np

In [14]:
data = np.loadtxt('C:\\Users\\Матвей\\Documents\\mirea\\minutes_n_ingredients.csv', delimiter=',', dtype='int32', skiprows=1)

In [15]:
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [16]:
import numpy as np

mean_values = np.mean(data[:, 1:], axis=0)

min_values = np.min(data[:, 1:], axis=0)

max_values = np.max(data[:, 1:], axis=0)

median_values = np.median(data[:, 1:], axis=0)

print("Среднее значение по столбцам (кроме первого):", mean_values)
print("Минимум по столбцам (кроме первого):", min_values)
print("Максимум по столбцам (кроме первого):", max_values)
print("Медиана по столбцам (кроме первого):", median_values)

Среднее значение по столбцам (кроме первого): [2.16010017e+04 9.05528000e+00]
Минимум по столбцам (кроме первого): [0 1]
Максимум по столбцам (кроме первого): [2147483647         39]
Медиана по столбцам (кроме первого): [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [17]:
import numpy as np
quantile_75 = np.quantile(data[:, 1], 0.75)
data[:, 1] = np.where(data[:, 1] > quantile_75, quantile_75, data[:, 1])
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [19]:
import numpy as np
zero_duration_count = np.sum(data[:, 1] == 0)
data[:, 1] = np.where(data[:, 1] == 0, 1, data[:, 1])
print("Количество рецептов с продолжительностью выполнения, равной нулю:", zero_duration_count)
print(data[:5])

Количество рецептов с продолжительностью выполнения, равной нулю: 0
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [20]:
import numpy as np
unique_recipes = np.unique(data[:, 0])
unique_recipes_count = len(unique_recipes)
print("Количество уникальных рецептов:", unique_recipes_count)

Количество уникальных рецептов: 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [21]:
import numpy as np
unique_ingredient_counts = np.unique(data[:, 2])
unique_count_values_count = len(unique_ingredient_counts)
print("Количество различных значений количества ингредиентов:", unique_count_values_count)
print("Различные значения количества ингредиентов:", unique_ingredient_counts)

Количество различных значений количества ингредиентов: 37
Различные значения количества ингредиентов: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [22]:
filtered_data = data[data[:, 2] <= 5]
print(filtered_data[:5])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 [484223     18      4]
 [ 63150     65      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [23]:
ingredients_per_minute = data[:, 2] / data[:, 1]
max_ingredients_per_minute = np.max(ingredients_per_minute)
print("Максимальное количество ингредиентов на минуту:", max_ingredients_per_minute)

Максимальное количество ингредиентов на минуту: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [24]:
sorted_data = data[data[:, 1].argsort()]
top_100_recipes = sorted_data[-100:]
mean_ingredients_top_100 = np.mean(top_100_recipes[:, 2])
print("Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью:", mean_ingredients_top_100)

Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: 9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [25]:
import numpy as np
random_indices = np.random.choice(data.shape[0], size=10, replace=False)
for index in random_indices:
    print("Рецепт ID:", data[index, 0])
    print("Продолжительность выполнения (минуты):", data[index, 1])
    print("Количество ингредиентов:", data[index, 2])
    print()  

Рецепт ID: 247260
Продолжительность выполнения (минуты): 20
Количество ингредиентов: 12

Рецепт ID: 438251
Продолжительность выполнения (минуты): 40
Количество ингредиентов: 16

Рецепт ID: 480179
Продолжительность выполнения (минуты): 65
Количество ингредиентов: 19

Рецепт ID: 392963
Продолжительность выполнения (минуты): 20
Количество ингредиентов: 6

Рецепт ID: 392683
Продолжительность выполнения (минуты): 65
Количество ингредиентов: 10

Рецепт ID: 279529
Продолжительность выполнения (минуты): 60
Количество ингредиентов: 8

Рецепт ID: 49663
Продолжительность выполнения (минуты): 65
Количество ингредиентов: 10

Рецепт ID: 120495
Продолжительность выполнения (минуты): 15
Количество ингредиентов: 6

Рецепт ID: 454181
Продолжительность выполнения (минуты): 25
Количество ингредиентов: 12

Рецепт ID: 254586
Продолжительность выполнения (минуты): 40
Количество ингредиентов: 11



11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [26]:
import numpy as np
mean_ingredients = np.mean(data[:, 2])
less_than_mean_count = np.sum(data[:, 2] < mean_ingredients)
percentage_less_than_mean = (less_than_mean_count / len(data)) * 100
print("Процент рецептов с количеством ингредиентов меньше среднего:", percentage_less_than_mean, "%")

Процент рецептов с количеством ингредиентов меньше среднего: 58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [27]:
data_with_simple_column = np.hstack((data, np.zeros((data.shape[0], 1), dtype=int)))
simple_recipes_indices = (data[:, 1] <= 20) & (data[:, 2] <= 5)
data_with_simple_column[:, -1] = np.where(simple_recipes_indices, 1, 0)
print(data_with_simple_column[:5])

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [157911     60     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [28]:
simple_recipes_count = np.sum(data_with_simple_column[:, -1] == 1)
total_recipes_count = data_with_simple_column.shape[0]
percentage_simple_recipes = (simple_recipes_count / total_recipes_count) * 100
print("Процент 'простых' рецептов в датасете:", percentage_simple_recipes, "%")

Процент 'простых' рецептов в датасете: 9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [29]:
short_recipes = data[data[:, 1] < 10]
standard_recipes = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long_recipes = data[data[:, 1] >= 20]

max_short_recipes = min(len(short_recipes), 10)  
max_standard_recipes = min(len(standard_recipes), 10)  
max_long_recipes = min(len(long_recipes), 10)  

three_dimensional_array = np.zeros((3, max(max_short_recipes, max_standard_recipes, max_long_recipes), data.shape[1]))

three_dimensional_array[0, :max_short_recipes, :] = short_recipes[:max_short_recipes, :]
three_dimensional_array[1, :max_standard_recipes, :] = standard_recipes[:max_standard_recipes, :]
three_dimensional_array[2, :max_long_recipes, :] = long_recipes[:max_long_recipes, :]

print("Форма полученного трехмерного массива:", three_dimensional_array.shape)


Форма полученного трехмерного массива: (3, 10, 3)
